<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

/**
 * App\Models\ShippingZone
 *
 * @property int $id
 * @property string|null $title
 * @property string|null $description
 * @property string $fee
 * @property int $enable
 * @property int $sort_num
 * @method static Builder|ShippingZone newModelQuery()
 * @method static Builder|ShippingZone newQuery()
 * @method static Builder|ShippingZone query()
 * @method static Builder|ShippingZone whereDescription($value)
 * @method static Builder|ShippingZone whereEnable($value)
 * @method static Builder|ShippingZone whereFee($value)
 * @method static Builder|ShippingZone whereId($value)
 * @method static Builder|ShippingZone whereSortNum($value)
 * @method static Builder|ShippingZone whereTitle($value)
 * @mixin \Eloquent
 */
class ShippingZone extends Model
{
    //use HasFactory;

    protected $table = 'shipping_zone';
    protected $primaryKey = 'id';
    protected $fillable = ['title', 'description', 'fee', 'sort_num'];
    public $timestamps = false;

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::addGlobalScope('sort', function (Builder $builder) {
            return $builder->orderBy('sort_num', 'asc');
        });
    }
}
