<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

/**
 * App\Models\Shortcut
 *
 * @property int $id
 * @property string|null $type
 * @property string|null $content
 * @property int|null $sort_num
 * @method static Builder|Shortcut newModelQuery()
 * @method static Builder|Shortcut newQuery()
 * @method static Builder|Shortcut query()
 * @method static Builder|Shortcut whereContent($value)
 * @method static Builder|Shortcut whereId($value)
 * @method static Builder|Shortcut whereSortNum($value)
 * @method static Builder|Shortcut whereType($value)
 * @mixin \Eloquent
 */
class Shortcut extends Model
{
    protected $table = 'shortcut';
    protected $fillable = ['type', 'content', 'sort_num'];
    protected $hidden = ['type'];

    public $timestamps = false;

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::addGlobalScope('sort', function (Builder $builder) {
            return $builder->orderBy('sort_num')->orderBy('id');
        });
    }
}
