<?php

namespace App\Models;

use App\Models\Traits\HasDates;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

/**
 * App\Models\Snippet
 *
 * @property int $id 主键
 * @property string|null $name 名称
 * @property string|null $content 内容
 * @property string|null $link 链接
 * @property \Illuminate\Support\Carbon|null $created_at 创建时间
 * @property \Illuminate\Support\Carbon|null $updated_at 更新时间
 * @method static \Illuminate\Database\Eloquent\Builder|Snippet newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|Snippet newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|Snippet query()
 * @method static \Illuminate\Database\Eloquent\Builder|Snippet whereContent($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Snippet whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Snippet whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Snippet whereLink($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Snippet whereName($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Snippet whereUpdatedAt($value)
 * @mixin \Eloquent
 */
class Snippet extends Model
{
    use HasFactory, HasDates;

    protected $table = 'snippet';
    protected $fillable = ['name', 'content', 'link'];

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::saved(function (Snippet $snippet) {
            cache()->forever('snippet-' . $snippet->id, $snippet);
        });
    }
}
